version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
    volumes:
      - ./storage:/app/storage
      - ./data:/app/data
    command: python run_api.py
    restart: unless-stopped

  ui:
    build: .
    ports:
      - "8501:8501"
    environment:
      - UI_PORT=8501
    volumes:
      - ./storage:/app/storage
      - ./data:/app/data
    command: python run_ui.py
    restart: unless-stopped
    depends_on:
      - api

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
